from Project import *
print('                       Modern Town')
asktime = input('night/day?')
if asktime == 'day':
    print('generating...')
    back()
    ground()
    house_1()
    window_1()
    window_2()
    window_3()
    window_4()
    window_5()
    window_6()
    window_7()
    window_8()
    door_1()
    door_line()
    tree()
    leave()
    square()
    window_9()
    door_2()
    handle()
    triangle_2()
    sun()
    hideturtle()
    exitonclick()
if asktime == 'night':
    print('generating...')
    back_2()
    ground()
    house_1()
    window_1()
    window_2()
    window_3()
    window_4()
    window_5()
    window_6()
    window_7()
    window_8()
    door_1()
    door_line()
    tree()
    leave()
    square()
    window_9()
    door_2()
    handle()
    triangle_2()
    moon()
    end_fill()
    hideturtle()
    penup()
    exitonclick()
